<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-03-03">
<meta name="description" content="It’s time we took an honest look at who is hurt most by the transfer portal">

<title>An Honest Conversation About The Transfer Portal – bendemouth.github.io</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">bendemouth.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/bendemouth"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">An Honest Conversation About The Transfer Portal</h1>
                  <div>
        <div class="description">
          It’s time we took an honest look at who is hurt most by the transfer portal
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">College Football</div>
                <div class="quarto-category">Sports Analytics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 3, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>College football has experienced monumental changes over the last six and a half years since the launch of the NCAA Transfer Portal. Combined with the advent of (legalized) Name, Image, and Likeness payments, collegiate athletes now have unprecedented levels of autonomy over their careers. Proponents of The Portal laud the addition for allowing players to be treated like professional athletes and be compensated according to their fair market values. Collegiate athletics are a multi-billion dollar industry after all. Critics say that it is ruining the sport by eroding tradition and watering down, if not removing entirely, the student portion of student athlete.</p>
<p>If you are looking for another blog with some takes about whether or not the transfer portal is good for The Sport™, there are plenty of those elsewhere. I’m interested in seeing how much roster turnover and, by extension, the Transfer Portal matters for team success.</p>
<p>I’m particularly interested in the Non-Power Conference teams. One of the biggest criticisms from the people most affected by the Transfer Portal is that the lower level teams get picked clean by the bigger programs each off-season. I want to see if that is true and, if it is, to what effect.</p>
<p>I’m pulling data from the <a href="https://github.com/CFBD/cfbd-python">cfbd-python library</a> for this post. If you like college football, this API is a must for your data analysis. A note on the API: you must sign up for an API key in order to use this it. It is very easy to get one and it is generally sent out very quickly after you sign up. I have a cell block hidden below my imports that configures my API key so I can make requests, so you will not be able to replicate my code simply from copying and pasting. Follow the documentation to configure your API and you’ll be golden.</p>
<div id="cell-2" class="cell" data-execution_count="560">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cfbd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cfbd.rest <span class="im">import</span> ApiException</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cfbd.models.team_record <span class="im">import</span> TeamRecord</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pandas <span class="im">import</span> json_normalize</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.offsetbox <span class="im">import</span> OffsetImage, AnnotationBbox</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-4" class="cell" data-execution_count="562">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>client <span class="op">=</span> cfbd.ApiClient(configuration)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>teams_api <span class="op">=</span> cfbd.TeamsApi(client)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>players_api <span class="op">=</span> cfbd.PlayersApi(client)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>games_api <span class="op">=</span> cfbd.GamesApi(client)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>players_api <span class="op">=</span> cfbd.PlayersApi(client)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>returning_production_response <span class="op">=</span> []</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>records_response <span class="op">=</span> []</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>transfer_response <span class="op">=</span> []</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    teams_response <span class="op">=</span> teams_api.get_fbs_teams() <span class="co"># Get a list of all FBS teams</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> year <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2021</span>, <span class="dv">2025</span>): <span class="co"># Get data for 2021-2024</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        returning_production_response <span class="op">+=</span> players_api.get_returning_production(year<span class="op">=</span>year) <span class="co"># Returning production</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        records_response <span class="op">+=</span> games_api.get_team_records(year<span class="op">=</span>year) <span class="co"># Team records</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        transfer_response <span class="op">+=</span> players_api.get_transfer_portal(year<span class="op">=</span>year) <span class="co"># Transfer players</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> ApiException <span class="im">as</span> e:</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Exception when calling StatsApi-&gt;get_stats_seasons: </span><span class="sc">%s</span><span class="ch">\n</span><span class="st">"</span> <span class="op">%</span> e)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Status code: </span><span class="sc">%s</span><span class="st">"</span> <span class="op">%</span> e.status)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Data response comes as object, we need to convert them to dictionaries</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>team_dicts <span class="op">=</span> [<span class="bu">vars</span>(team) <span class="cf">for</span> team <span class="kw">in</span> teams_response]</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>teams_df <span class="op">=</span> pd.DataFrame(team_dicts)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>returning_production_dicts <span class="op">=</span> [<span class="bu">vars</span>(returning_production) <span class="cf">for</span> returning_production <span class="kw">in</span> returning_production_response]</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>returning_production_df <span class="op">=</span> pd.DataFrame(returning_production_dicts)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>records_dicts <span class="op">=</span> [<span class="bu">vars</span>(record) <span class="cf">for</span> record <span class="kw">in</span> records_response]</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>records_df <span class="op">=</span> pd.DataFrame(records_dicts)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="co"># The records have nested objects in these columns, so we need to extract that data into their own columns</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>nested_columns <span class="op">=</span> [<span class="st">"_total"</span>, <span class="st">"_conference_games"</span>, <span class="st">"_home_games"</span>, <span class="st">"_away_games"</span>]</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column <span class="kw">in</span> nested_columns:</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    records_df[column] <span class="op">=</span> records_df[column].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">vars</span>(x) <span class="cf">if</span> x <span class="cf">else</span> {})</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    normalized_df <span class="op">=</span> pd.json_normalize(records_df[column])</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    normalized_df.columns <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>column[<span class="dv">1</span>:]<span class="sc">}</span><span class="ss">_</span><span class="sc">{</span>subcolumn<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> subcolumn <span class="kw">in</span> normalized_df.columns]</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>    records_df <span class="op">=</span> pd.concat([records_df, normalized_df], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    records_df.drop(columns<span class="op">=</span>[column], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>transfer_dicts <span class="op">=</span> [<span class="bu">vars</span>(transfer) <span class="cf">for</span> transfer <span class="kw">in</span> transfer_response]</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>transfer_df <span class="op">=</span> pd.DataFrame(transfer_dicts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This dataframe gets us a list of all FBS college football teams.</p>
<div id="cell-6" class="cell" data-execution_count="563">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>teams_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="563">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">_configuration</th>
<th data-quarto-table-cell-role="th">_id</th>
<th data-quarto-table-cell-role="th">_school</th>
<th data-quarto-table-cell-role="th">_mascot</th>
<th data-quarto-table-cell-role="th">_abbreviation</th>
<th data-quarto-table-cell-role="th">_alt_name_1</th>
<th data-quarto-table-cell-role="th">_alt_name_2</th>
<th data-quarto-table-cell-role="th">_alt_name_3</th>
<th data-quarto-table-cell-role="th">_classification</th>
<th data-quarto-table-cell-role="th">_conference</th>
<th data-quarto-table-cell-role="th">_division</th>
<th data-quarto-table-cell-role="th">_color</th>
<th data-quarto-table-cell-role="th">_alt_color</th>
<th data-quarto-table-cell-role="th">_logos</th>
<th data-quarto-table-cell-role="th">_twitter</th>
<th data-quarto-table-cell-role="th">_location</th>
<th data-quarto-table-cell-role="th">discriminator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2005</td>
<td>Air Force</td>
<td>Falcons</td>
<td>AFA</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>Mountain West</td>
<td>None</td>
<td>#004a7b</td>
<td>#ffffff</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/200...</td>
<td>@AF_Football</td>
<td>{'capacity': 46692.0,\n 'city': 'Colorado Spri...</td>
<td>None</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2006</td>
<td>Akron</td>
<td>Zips</td>
<td>AKR</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>Mid-American</td>
<td>None</td>
<td>#00285e</td>
<td>#84754e</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/200...</td>
<td>@ZipsFB</td>
<td>{'capacity': 30000.0,\n 'city': 'Akron',\n 'co...</td>
<td>None</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>333</td>
<td>Alabama</td>
<td>Crimson Tide</td>
<td>ALA</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>SEC</td>
<td>None</td>
<td>#9e1632</td>
<td>#ffffff</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/333...</td>
<td>@AlabamaFTBL</td>
<td>{'capacity': 101821.0,\n 'city': 'Tuscaloosa',...</td>
<td>None</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2026</td>
<td>App State</td>
<td>Mountaineers</td>
<td>APP</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>Sun Belt</td>
<td>East</td>
<td>#ffcc00</td>
<td>#222222</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/202...</td>
<td>@AppState_FB</td>
<td>{'capacity': 30000.0,\n 'city': 'Boone',\n 'co...</td>
<td>None</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>12</td>
<td>Arizona</td>
<td>Wildcats</td>
<td>ARIZ</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>Big 12</td>
<td>None</td>
<td>#0c234b</td>
<td>#ab0520</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/12....</td>
<td>@ArizonaFBall</td>
<td>{'capacity': 50782.0,\n 'city': 'Tucson',\n 'c...</td>
<td>None</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This dataframe has returning production for each team. This gives us a percentage of usage returning and PPA numbers. PPA (sometimes called EPA) is a measure of how many expected points are added on a given play.</p>
<div id="cell-8" class="cell" data-execution_count="564">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>returning_production_df <span class="op">=</span> returning_production_df[returning_production_df[<span class="st">'_team'</span>].isin(teams_df[<span class="st">'_school'</span>])]</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>returning_production_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="564">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">_configuration</th>
<th data-quarto-table-cell-role="th">_season</th>
<th data-quarto-table-cell-role="th">_team</th>
<th data-quarto-table-cell-role="th">_conference</th>
<th data-quarto-table-cell-role="th">_total_ppa</th>
<th data-quarto-table-cell-role="th">_total_passing_ppa</th>
<th data-quarto-table-cell-role="th">_total_receiving_ppa</th>
<th data-quarto-table-cell-role="th">_total_rushing_ppa</th>
<th data-quarto-table-cell-role="th">_percent_ppa</th>
<th data-quarto-table-cell-role="th">_percent_passing_ppa</th>
<th data-quarto-table-cell-role="th">_percent_receiving_ppa</th>
<th data-quarto-table-cell-role="th">_percent_rushing_ppa</th>
<th data-quarto-table-cell-role="th">_usage</th>
<th data-quarto-table-cell-role="th">_passing_usage</th>
<th data-quarto-table-cell-role="th">_receiving_usage</th>
<th data-quarto-table-cell-role="th">_rushing_usage</th>
<th data-quarto-table-cell-role="th">discriminator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>Air Force</td>
<td>Mountain West</td>
<td>126.8</td>
<td>35.0</td>
<td>20.8</td>
<td>71.0</td>
<td>0.742</td>
<td>1.000</td>
<td>0.540</td>
<td>0.724</td>
<td>0.724</td>
<td>1.000</td>
<td>0.745</td>
<td>0.662</td>
<td>None</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>Akron</td>
<td>Mid-American</td>
<td>27.5</td>
<td>-19.8</td>
<td>23.1</td>
<td>24.2</td>
<td>0.611</td>
<td>0.756</td>
<td>0.545</td>
<td>0.826</td>
<td>0.805</td>
<td>0.902</td>
<td>0.694</td>
<td>0.788</td>
<td>None</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>Alabama</td>
<td>SEC</td>
<td>148.6</td>
<td>16.7</td>
<td>90.1</td>
<td>41.7</td>
<td>0.198</td>
<td>0.058</td>
<td>0.268</td>
<td>0.336</td>
<td>0.260</td>
<td>0.072</td>
<td>0.349</td>
<td>0.368</td>
<td>None</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>Arizona</td>
<td>Pac-12</td>
<td>40.2</td>
<td>-15.2</td>
<td>41.4</td>
<td>14.0</td>
<td>0.442</td>
<td>-2.980</td>
<td>0.704</td>
<td>0.515</td>
<td>0.478</td>
<td>0.427</td>
<td>0.648</td>
<td>0.371</td>
<td>None</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>Arizona State</td>
<td>Pac-12</td>
<td>127.8</td>
<td>29.8</td>
<td>47.1</td>
<td>50.8</td>
<td>0.983</td>
<td>1.000</td>
<td>0.946</td>
<td>1.000</td>
<td>0.966</td>
<td>1.000</td>
<td>0.855</td>
<td>1.000</td>
<td>None</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Get the records for each team each season.</p>
<div id="cell-10" class="cell" data-execution_count="565">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>records_df <span class="op">=</span> records_df[records_df[<span class="st">'_team'</span>].isin(teams_df[<span class="st">'_school'</span>])]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>records_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="565">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">_configuration</th>
<th data-quarto-table-cell-role="th">_year</th>
<th data-quarto-table-cell-role="th">_team_id</th>
<th data-quarto-table-cell-role="th">_team</th>
<th data-quarto-table-cell-role="th">_conference</th>
<th data-quarto-table-cell-role="th">_division</th>
<th data-quarto-table-cell-role="th">_expected_wins</th>
<th data-quarto-table-cell-role="th">discriminator</th>
<th data-quarto-table-cell-role="th">total__configuration</th>
<th data-quarto-table-cell-role="th">total__games</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">home_games__wins</th>
<th data-quarto-table-cell-role="th">home_games__losses</th>
<th data-quarto-table-cell-role="th">home_games__ties</th>
<th data-quarto-table-cell-role="th">home_games_discriminator</th>
<th data-quarto-table-cell-role="th">away_games__configuration</th>
<th data-quarto-table-cell-role="th">away_games__games</th>
<th data-quarto-table-cell-role="th">away_games__wins</th>
<th data-quarto-table-cell-role="th">away_games__losses</th>
<th data-quarto-table-cell-role="th">away_games__ties</th>
<th data-quarto-table-cell-role="th">away_games_discriminator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>62</td>
<td>Hawai'i</td>
<td>Mountain West</td>
<td>West</td>
<td>6.3</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>13</td>
<td>...</td>
<td>4</td>
<td>2</td>
<td>0</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>7</td>
<td>2</td>
<td>5</td>
<td>0</td>
<td>None</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>2306</td>
<td>Kansas State</td>
<td>Big 12</td>
<td></td>
<td>7.4</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>13</td>
<td>...</td>
<td>4</td>
<td>3</td>
<td>0</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>4</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>None</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">13</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>2751</td>
<td>Wyoming</td>
<td>Mountain West</td>
<td>Mountain</td>
<td>7.6</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>13</td>
<td>...</td>
<td>3</td>
<td>3</td>
<td>0</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>6</td>
<td>3</td>
<td>3</td>
<td>0</td>
<td>None</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>213</td>
<td>Penn State</td>
<td>Big Ten</td>
<td>East</td>
<td>7.1</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>13</td>
<td>...</td>
<td>5</td>
<td>2</td>
<td>0</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>5</td>
<td>2</td>
<td>3</td>
<td>0</td>
<td>None</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">27</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>2021</td>
<td>2649</td>
<td>Toledo</td>
<td>Mid-American</td>
<td>West</td>
<td>8.0</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>13</td>
<td>...</td>
<td>3</td>
<td>3</td>
<td>0</td>
<td>None</td>
<td>&lt;cfbd.configuration.Configuration object at 0x...</td>
<td>6</td>
<td>4</td>
<td>2</td>
<td>0</td>
<td>None</td>
</tr>
</tbody>
</table>

<p>5 rows × 32 columns</p>
</div>
</div>
</div>
<p>And finally, get the number of incoming transfers for a season. These are grouped based on transfer date. Because the transfer portal windows are all in the same year in which a season is played, we do not need to lag this by a year. For example, if a player transfers in May of 2025, he would be eligible to play for the fall 2025 season.</p>
<div id="cell-12" class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>transfer_df <span class="op">=</span> transfer_df.dropna(subset<span class="op">=</span>[<span class="st">'_destination'</span>, <span class="st">'_origin'</span>])</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>transfers_in <span class="op">=</span> (</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    transfer_df.groupby([<span class="st">'_destination'</span>, <span class="st">'_season'</span>])</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    .size()</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    .reset_index(name<span class="op">=</span><span class="st">'total_transfers_in'</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>transfers_out <span class="op">=</span> (</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    transfer_df.groupby([<span class="st">'_origin'</span>, <span class="st">'_season'</span>])</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    .size()</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    .reset_index(name<span class="op">=</span><span class="st">'total_transfers_out'</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>transfer_df <span class="op">=</span> (</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    pd.merge(</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>        transfers_in, transfers_out,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>        left_on<span class="op">=</span>[<span class="st">'_destination'</span>, <span class="st">'_season'</span>],</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>        right_on<span class="op">=</span>[<span class="st">'_origin'</span>, <span class="st">'_season'</span>],</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>        how<span class="op">=</span><span class="st">'outer'</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>transfer_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="566">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">_destination</th>
<th data-quarto-table-cell-role="th">_season</th>
<th data-quarto-table-cell-role="th">total_transfers_in</th>
<th data-quarto-table-cell-role="th">_origin</th>
<th data-quarto-table-cell-role="th">total_transfers_out</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Abilene Christian</td>
<td>2021</td>
<td>4.0</td>
<td>Abilene Christian</td>
<td>2.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Abilene Christian</td>
<td>2022</td>
<td>9.0</td>
<td>Abilene Christian</td>
<td>4.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Abilene Christian</td>
<td>2023</td>
<td>4.0</td>
<td>Abilene Christian</td>
<td>2.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Abilene Christian</td>
<td>2024</td>
<td>13.0</td>
<td>Abilene Christian</td>
<td>2.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Air Force</td>
<td>2021</td>
<td>2.0</td>
<td>Air Force</td>
<td>2.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Combine them all together and…</p>
<div id="cell-14" class="cell" data-execution_count="567">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine data frames with a series of merges</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> teams_df.merge(records_df.set_index(<span class="st">'_team_id'</span>), how<span class="op">=</span><span class="st">"inner"</span>, </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                    left_on<span class="op">=</span>[<span class="st">'_id'</span>], right_on<span class="op">=</span>[<span class="st">'_team_id'</span>])</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.merge(returning_production_df, how<span class="op">=</span><span class="st">'left'</span>, </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>              left_on<span class="op">=</span>[<span class="st">'_team'</span>, <span class="st">'_year'</span>], right_on<span class="op">=</span>[<span class="st">'_team'</span>, <span class="st">'_season'</span>])</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.merge(transfer_df, how<span class="op">=</span><span class="st">'left'</span>, </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>              left_on<span class="op">=</span>[<span class="st">'_school'</span>, <span class="st">'_year'</span>], right_on<span class="op">=</span>[<span class="st">'_destination'</span>, <span class="st">'_season'</span>])</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Get rid of columns that were duplicated in the merges and others that are not needed</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.loc[:, <span class="op">~</span>df.columns.<span class="bu">str</span>.endswith((<span class="st">'_x'</span>, <span class="st">'_y'</span>)) </span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>            <span class="op">&amp;</span> <span class="op">~</span>df.columns.<span class="bu">str</span>.contains(<span class="st">'_alt_name'</span>)  </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>            <span class="op">&amp;</span> <span class="op">~</span>df.columns.<span class="bu">str</span>.contains(<span class="st">'discriminator'</span>) </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>            <span class="op">&amp;</span> <span class="op">~</span>df.columns.<span class="bu">str</span>.contains(<span class="st">'configuration'</span>)]</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop records that are missing the data that we will need</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>usage_ppa_transfer_cols <span class="op">=</span> df.columns[df.columns.<span class="bu">str</span>.endswith((<span class="st">'_usage'</span>, <span class="st">'_ppa'</span>, <span class="st">'total_transfers_in'</span>))].tolist()</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna(subset<span class="op">=</span>usage_ppa_transfer_cols)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="567">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">_id</th>
<th data-quarto-table-cell-role="th">_school</th>
<th data-quarto-table-cell-role="th">_mascot</th>
<th data-quarto-table-cell-role="th">_abbreviation</th>
<th data-quarto-table-cell-role="th">_classification</th>
<th data-quarto-table-cell-role="th">_color</th>
<th data-quarto-table-cell-role="th">_alt_color</th>
<th data-quarto-table-cell-role="th">_logos</th>
<th data-quarto-table-cell-role="th">_twitter</th>
<th data-quarto-table-cell-role="th">_location</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">_percent_receiving_ppa</th>
<th data-quarto-table-cell-role="th">_percent_rushing_ppa</th>
<th data-quarto-table-cell-role="th">_usage</th>
<th data-quarto-table-cell-role="th">_passing_usage</th>
<th data-quarto-table-cell-role="th">_receiving_usage</th>
<th data-quarto-table-cell-role="th">_rushing_usage</th>
<th data-quarto-table-cell-role="th">_destination</th>
<th data-quarto-table-cell-role="th">total_transfers_in</th>
<th data-quarto-table-cell-role="th">_origin</th>
<th data-quarto-table-cell-role="th">total_transfers_out</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2005</td>
<td>Air Force</td>
<td>Falcons</td>
<td>AFA</td>
<td>None</td>
<td>#004a7b</td>
<td>#ffffff</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/200...</td>
<td>@AF_Football</td>
<td>{'capacity': 46692.0,\n 'city': 'Colorado Spri...</td>
<td>...</td>
<td>0.540</td>
<td>0.724</td>
<td>0.724</td>
<td>1.000</td>
<td>0.745</td>
<td>0.662</td>
<td>Air Force</td>
<td>2.0</td>
<td>Air Force</td>
<td>2.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>2006</td>
<td>Akron</td>
<td>Zips</td>
<td>AKR</td>
<td>None</td>
<td>#00285e</td>
<td>#84754e</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/200...</td>
<td>@ZipsFB</td>
<td>{'capacity': 30000.0,\n 'city': 'Akron',\n 'co...</td>
<td>...</td>
<td>0.545</td>
<td>0.826</td>
<td>0.805</td>
<td>0.902</td>
<td>0.694</td>
<td>0.788</td>
<td>Akron</td>
<td>3.0</td>
<td>Akron</td>
<td>3.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>2006</td>
<td>Akron</td>
<td>Zips</td>
<td>AKR</td>
<td>None</td>
<td>#00285e</td>
<td>#84754e</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/200...</td>
<td>@ZipsFB</td>
<td>{'capacity': 30000.0,\n 'city': 'Akron',\n 'co...</td>
<td>...</td>
<td>0.349</td>
<td>0.155</td>
<td>0.485</td>
<td>0.343</td>
<td>0.290</td>
<td>0.806</td>
<td>Akron</td>
<td>15.0</td>
<td>Akron</td>
<td>4.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6</td>
<td>2006</td>
<td>Akron</td>
<td>Zips</td>
<td>AKR</td>
<td>None</td>
<td>#00285e</td>
<td>#84754e</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/200...</td>
<td>@ZipsFB</td>
<td>{'capacity': 30000.0,\n 'city': 'Akron',\n 'co...</td>
<td>...</td>
<td>0.614</td>
<td>0.893</td>
<td>0.758</td>
<td>0.995</td>
<td>0.573</td>
<td>0.596</td>
<td>Akron</td>
<td>4.0</td>
<td>Akron</td>
<td>6.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>2006</td>
<td>Akron</td>
<td>Zips</td>
<td>AKR</td>
<td>None</td>
<td>#00285e</td>
<td>#84754e</td>
<td>[http://a.espncdn.com/i/teamlogos/ncaa/500/200...</td>
<td>@ZipsFB</td>
<td>{'capacity': 30000.0,\n 'city': 'Akron',\n 'co...</td>
<td>...</td>
<td>0.681</td>
<td>0.490</td>
<td>0.759</td>
<td>0.994</td>
<td>0.666</td>
<td>0.525</td>
<td>Akron</td>
<td>15.0</td>
<td>Akron</td>
<td>16.0</td>
</tr>
</tbody>
</table>

<p>5 rows × 46 columns</p>
</div>
</div>
</div>
<p>…voila! We have something that we can more easily work with now.</p>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>Before going looking at how transfer are affecting production, I want to get more familiar with the data set and see if we can learn anything interesting in there.</p>
<div id="cell-16" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>transfers_by_season <span class="op">=</span> df[[<span class="st">'_year'</span>, <span class="st">'total_transfers_in'</span>]].groupby(<span class="st">'_year'</span>).<span class="bu">sum</span>().reset_index()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>transfers_by_season[<span class="st">'pct_change'</span>] <span class="op">=</span> transfers_by_season[<span class="st">'total_transfers_in'</span>].pct_change() <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> plt.bar(transfers_by_season[<span class="st">'_year'</span>], transfers_by_season[<span class="st">'total_transfers_in'</span>], color<span class="op">=</span><span class="st">'#012d69'</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, bar <span class="kw">in</span> <span class="bu">enumerate</span>(bars):</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> i <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>        pct_change <span class="op">=</span> transfers_by_season[<span class="st">'pct_change'</span>].iloc[i]</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>        label <span class="op">=</span> <span class="ss">f"</span><span class="ch">\u25B2</span><span class="ss"> </span><span class="sc">{</span>pct_change<span class="sc">:.1f}</span><span class="ss">%"</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>        plt.text(bar.get_x() <span class="op">+</span> bar.get_width() <span class="op">/</span> <span class="dv">2</span>, bar.get_height() <span class="op">+</span> <span class="dv">10</span>, label, ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, color<span class="op">=</span><span class="st">'green'</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>plt.xticks(ticks<span class="op">=</span>transfers_by_season[<span class="st">'_year'</span>])</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Season'</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Total Transfers'</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Transfers In Across FBS From 2021-2024'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="568">
<pre><code>Text(0.5, 1.0, 'Transfers In Across FBS From 2021-2024')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="an-honest-conversation-about-the-transfer-portal_files/figure-html/cell-10-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Transfers have increased year over year each year this decade with no real signs of slowing down. Whatever effect is made from this new Transfer Portal is likely to continue to grow moving forward until some sort of equilibrium is found.</p>
<p>But where are these transfers going?</p>
<div id="cell-18" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>transfers_in_by_conference <span class="op">=</span> df[[<span class="st">'_conference'</span>, <span class="st">'total_transfers_in'</span>]].groupby(<span class="st">'_conference'</span>).<span class="bu">sum</span>().reset_index()</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>power_conferences <span class="op">=</span> [<span class="st">'ACC'</span>, <span class="st">'Big 12'</span>, <span class="st">'Big Ten'</span>, <span class="st">'Pac-12'</span>, <span class="st">'SEC'</span>]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'#ad0004'</span> <span class="cf">if</span> conference <span class="kw">in</span> power_conferences <span class="cf">else</span> <span class="st">'#012d69'</span> <span class="cf">for</span> conference <span class="kw">in</span> transfers_in_by_conference[<span class="st">'_conference'</span>]]</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> plt.bar(transfers_in_by_conference[<span class="st">'_conference'</span>], transfers_in_by_conference[<span class="st">'total_transfers_in'</span>], color<span class="op">=</span>colors)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, bar <span class="kw">in</span> <span class="bu">enumerate</span>(bars):</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    transfers <span class="op">=</span> bar.get_height().astype(<span class="bu">int</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    plt.text(bars[i].get_x() <span class="op">+</span> bars[i].get_width() <span class="op">/</span> <span class="dv">2</span>, bars[i].get_height() <span class="op">+</span> <span class="dv">10</span>, transfers, </span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>             ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Conference'</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Total Transfers'</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Transfers In by FBS Conference'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="569">
<pre><code>Text(0.5, 1.0, 'Transfers In by FBS Conference')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="an-honest-conversation-about-the-transfer-portal_files/figure-html/cell-11-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This chart surprises me a bit. I would have expected that all of the Power Five conferences would be head and shoulders above all of the Group of Five conferences. In reality, the top end of G5 conferences are getting nearly as many transfers, if not more, than the Power Five conferences. Also, what are they doing in the AAC?</p>
<p>A quick point about conference realignment: because our data is up to the 2024 offseason, teams that played their first season in their new conference in 2024 are still counted towards their original conference. If they played a season in their new conference prior to 2024, those changes are accurately reflected. For example, all Washington and Oregon data still count towards the Pac-12, all Texas and Oklahoma data still count towards the Big 12. But 2021-2023 BYU counts towards FBS Independents, but 2024 BYU counts towards the Big 12.</p>
<div id="cell-20" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>transfers <span class="op">=</span> pd.DataFrame(transfer_dicts) <span class="co"># Remake transfers data frame without aggregation</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>transfers <span class="op">=</span> transfers.groupby(<span class="st">'_destination'</span>).agg({<span class="st">'_stars'</span>: <span class="st">'mean'</span>, <span class="st">'_season'</span>: <span class="st">'count'</span>}).rename({<span class="st">'_season'</span>: <span class="st">'total_transfers_in'</span>, <span class="st">'_stars'</span>: <span class="st">'avg_stars'</span>}, axis<span class="op">=</span><span class="dv">1</span>).reset_index()</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>transfers <span class="op">=</span> transfers.merge(teams_df[[<span class="st">'_id'</span>, <span class="st">'_school'</span>, <span class="st">'_conference'</span>]], how<span class="op">=</span><span class="st">'inner'</span>, left_on<span class="op">=</span>[<span class="st">'_destination'</span>], right_on<span class="op">=</span>[<span class="st">'_school'</span>]).drop(<span class="st">'_school'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>power_five_transfers <span class="op">=</span> transfers[transfers[<span class="st">'_conference'</span>].isin(power_conferences) <span class="op">|</span> transfers[<span class="st">'_destination'</span>].<span class="bu">str</span>.contains(<span class="st">'Notre Dame'</span>)]</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>g5_transfers <span class="op">=</span> transfers[<span class="op">~</span>transfers[<span class="st">'_conference'</span>].isin(power_conferences) <span class="op">&amp;</span> <span class="op">~</span>transfers[<span class="st">'_destination'</span>].<span class="bu">str</span>.contains(<span class="st">'Notre Dame'</span>)]</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to get logos from image folder. Variable 'logos_folder' is defined in the hidden cell</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># with API config. It is a local file path</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_image_path(<span class="bu">id</span>):</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> OffsetImage(plt.imread(<span class="ss">f"</span><span class="sc">{</span>logos_folder<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span><span class="bu">id</span><span class="sc">}</span><span class="ss">.png"</span>))</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plots</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].scatter(power_five_transfers[<span class="st">'avg_stars'</span>], power_five_transfers[<span class="st">'total_transfers_in'</span>], alpha<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Bind logo to data point</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x0, y0, <span class="bu">id</span> <span class="kw">in</span> <span class="bu">zip</span>(power_five_transfers[<span class="st">'avg_stars'</span>], power_five_transfers[<span class="st">'total_transfers_in'</span>], power_five_transfers[<span class="st">'_id'</span>]):</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    ab <span class="op">=</span> AnnotationBbox(get_image_path(<span class="bu">id</span>), (x0, y0), frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].add_artist(ab)</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axvline(power_five_transfers[<span class="st">'avg_stars'</span>].mean(), color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axhline(power_five_transfers[<span class="st">'total_transfers_in'</span>].mean(), color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">'Average Stars'</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylabel(<span class="st">'Total Transfers'</span>)</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlim(<span class="fl">2.7</span>, <span class="fl">3.7</span>)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylim(<span class="dv">0</span>, <span class="dv">105</span>)</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">'Power Five Transfers In (2021-2024)'</span>)</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].grid(<span class="va">True</span>)</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].scatter(g5_transfers[<span class="st">'avg_stars'</span>], g5_transfers[<span class="st">'total_transfers_in'</span>], alpha<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x0, y0, <span class="bu">id</span> <span class="kw">in</span> <span class="bu">zip</span>(g5_transfers[<span class="st">'avg_stars'</span>], g5_transfers[<span class="st">'total_transfers_in'</span>], g5_transfers[<span class="st">'_id'</span>]):</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>    ab <span class="op">=</span> AnnotationBbox(get_image_path(<span class="bu">id</span>), (x0, y0), frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].add_artist(ab)</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axvline(g5_transfers[<span class="st">'avg_stars'</span>].mean(), color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axhline(g5_transfers[<span class="st">'total_transfers_in'</span>].mean(), color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlabel(<span class="st">'Average Stars'</span>)</span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylabel(<span class="st">'Total Transfers'</span>)</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlim(<span class="fl">2.7</span>, <span class="fl">3.7</span>)</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylim(<span class="dv">0</span>, <span class="dv">105</span>)</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">'G5 Transfers In (2021-2024)'</span>)</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].grid(<span class="va">True</span>)</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribution plots</span></span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>sns.histplot(power_five_transfers[<span class="st">'total_transfers_in'</span>], label<span class="op">=</span><span class="st">"Power 5"</span>, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'#ad0004'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, ax<span class="op">=</span>ax[<span class="dv">0</span>])</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>sns.histplot(g5_transfers[<span class="st">'total_transfers_in'</span>], label<span class="op">=</span><span class="st">"G5"</span>, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'#012d69'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, ax<span class="op">=</span>ax[<span class="dv">0</span>])</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">"Total Transfers"</span>)</span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">"Distribution of Total Transfers In"</span>)</span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a>sns.histplot(power_five_transfers[<span class="st">'avg_stars'</span>], label<span class="op">=</span><span class="st">"Power 5"</span>, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'#ad0004'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, ax<span class="op">=</span>ax[<span class="dv">1</span>])</span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a>sns.histplot(g5_transfers[<span class="st">'avg_stars'</span>], label<span class="op">=</span><span class="st">"G5"</span>, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'#012d69'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, ax<span class="op">=</span>ax[<span class="dv">1</span>])</span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlabel(<span class="st">"Average Stars"</span>)</span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">"Distribution of Transfer In Star Ratings"</span>)</span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-66"><a href="#cb12-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-67"><a href="#cb12-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate effect power for average stars</span></span>
<span id="cb12-68"><a href="#cb12-68" aria-hidden="true" tabindex="-1"></a>n_power_five <span class="op">=</span> <span class="bu">len</span>(power_five_transfers)</span>
<span id="cb12-69"><a href="#cb12-69" aria-hidden="true" tabindex="-1"></a>n_g5 <span class="op">=</span> <span class="bu">len</span>(g5_transfers)</span>
<span id="cb12-70"><a href="#cb12-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-71"><a href="#cb12-71" aria-hidden="true" tabindex="-1"></a>std_power_five <span class="op">=</span> power_five_transfers[<span class="st">'avg_stars'</span>].std()</span>
<span id="cb12-72"><a href="#cb12-72" aria-hidden="true" tabindex="-1"></a>std_g5 <span class="op">=</span> g5_transfers[<span class="st">'avg_stars'</span>].std()</span>
<span id="cb12-73"><a href="#cb12-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-74"><a href="#cb12-74" aria-hidden="true" tabindex="-1"></a>pooled_std <span class="op">=</span> np.sqrt(((n_power_five <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> std_power_five<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> (n_g5 <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> std_g5<span class="op">**</span><span class="dv">2</span>) <span class="op">/</span> (n_power_five <span class="op">+</span> n_g5 <span class="op">-</span> <span class="dv">2</span>))</span>
<span id="cb12-75"><a href="#cb12-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-76"><a href="#cb12-76" aria-hidden="true" tabindex="-1"></a>cohens_d <span class="op">=</span> (power_five_transfers[<span class="st">'avg_stars'</span>].mean() <span class="op">-</span> g5_transfers[<span class="st">'avg_stars'</span>].mean()) <span class="op">/</span> pooled_std</span>
<span id="cb12-77"><a href="#cb12-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-78"><a href="#cb12-78" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cohen's D: </span><span class="sc">{</span>cohens_d<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="an-honest-conversation-about-the-transfer-portal_files/figure-html/cell-12-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="an-honest-conversation-about-the-transfer-portal_files/figure-html/cell-12-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's D: 1.60</code></pre>
</div>
</div>
<p>This tells me that there isn’t a whole lot of difference between Power Five and G5 in the quantity of transfers that are coming in to a program, but there is a big difference in the quality of transfers coming in. The average star rating for a player going to a Power Five school is 3.17, while the average star rating for a player going to a G5 school is 2.95. Cohen’s d score for the effect size of the difference between the two is a whopping 1.6, indicating a very massive difference between the two. Generally speaking, anything over a 0.8 is considered a strong effect size. We are doubling that here.</p>
</section>
<section id="are-g5-schools-getting-picked-clean" class="level2">
<h2 class="anchored" data-anchor-id="are-g5-schools-getting-picked-clean">Are G5 Schools Getting Picked Clean?</h2>
<p>We’ve talked a good bit about transfers but what about transfers out? As we discussed earlier, however, coaches at the G5 level often claim that their teams are scavenged by larger schools. We’ve already established that there are roughly the same quantity of transfers across levels and that power conference teams tend to get the better players, but that doesn’t necessarily tell me whether or not G5 teams are losing their best players. It’s reasonable to think that the better players are already at the Power Five teams. Perhaps the player movement is just players going from P5 to P5 or from G5 to G5.</p>
<div id="cell-22" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>transfers_out_by_conference <span class="op">=</span> df[[<span class="st">'_conference'</span>, <span class="st">'total_transfers_out'</span>]].groupby(<span class="st">'_conference'</span>).<span class="bu">sum</span>().reset_index()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'#ad0004'</span> <span class="cf">if</span> conference <span class="kw">in</span> power_conferences <span class="cf">else</span> <span class="st">'#012d69'</span> <span class="cf">for</span> conference <span class="kw">in</span> transfers_out_by_conference[<span class="st">'_conference'</span>]]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> plt.bar(transfers_out_by_conference[<span class="st">'_conference'</span>], transfers_out_by_conference[<span class="st">'total_transfers_out'</span>], color<span class="op">=</span>colors)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, bar <span class="kw">in</span> <span class="bu">enumerate</span>(bars):</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    transfers_number <span class="op">=</span> bar.get_height().astype(<span class="bu">int</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    plt.text(bars[i].get_x() <span class="op">+</span> bars[i].get_width() <span class="op">/</span> <span class="dv">2</span>, bars[i].get_height() <span class="op">+</span> <span class="dv">10</span>, transfers_number, </span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>             ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Conference'</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Total Transfers'</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Transfers Out by FBS Conference'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="571">
<pre><code>Text(0.5, 1.0, 'Transfers Out by FBS Conference')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="an-honest-conversation-about-the-transfer-portal_files/figure-html/cell-13-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Another surprise here from this chart. I would have expected that power conference teams have less roster turnover from the transfer portal. My thinking was that the players are at or near the pinnacle of college football, so they would be more likely to stay. That does not appear to be the case. Again, the AAC is an exception here, but other than them, all Power 5 conferences have more transfers out than the G5 conferences.</p>
<p>One thing that I think is interesting to note here is that there are a lot more players transferring out of FBS than are transferring in to FBS. This tells me that there are a lot of players going to FCS, DII, DIII, or NAIA schools. Hold on to this thought. I’m going to come back to that in a second.</p>
<p>So, how about the quality of the players transferring out? I think it is important to think about the quality of players that are already at each level again. P5 schools are going to naturally have better quality players. But if there is some similarity to level of player transferring out between P5 and G5, then it lends some credence to the idea that G5 teams are getting poached.</p>
<div id="cell-24" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>transfers_out <span class="op">=</span> pd.DataFrame(transfer_dicts) <span class="co"># Remake transfers data frame without aggregation</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>transfers_out <span class="op">=</span> transfers_out.dropna(subset<span class="op">=</span>[<span class="st">'_origin'</span>, <span class="st">'_destination'</span>])</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>transfers_out <span class="op">=</span> transfers_out.groupby(<span class="st">'_origin'</span>).agg({<span class="st">'_stars'</span>: <span class="st">'mean'</span>, <span class="st">'_season'</span>: <span class="st">'count'</span>}).rename({<span class="st">'_season'</span>: <span class="st">'total_transfers_out'</span>, <span class="st">'_stars'</span>: <span class="st">'avg_stars'</span>}, axis<span class="op">=</span><span class="dv">1</span>).reset_index()</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>transfers_out <span class="op">=</span> transfers_out.merge(teams_df[[<span class="st">'_id'</span>, <span class="st">'_school'</span>, <span class="st">'_conference'</span>]], how<span class="op">=</span><span class="st">'inner'</span>, left_on<span class="op">=</span>[<span class="st">'_origin'</span>], right_on<span class="op">=</span>[<span class="st">'_school'</span>]).drop(<span class="st">'_school'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>power_five_transfers <span class="op">=</span> transfers_out[transfers_out[<span class="st">'_conference'</span>].isin(power_conferences) <span class="op">|</span> transfers_out[<span class="st">'_origin'</span>].<span class="bu">str</span>.contains(<span class="st">'Notre Dame'</span>)]</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>g5_transfers <span class="op">=</span> transfers_out[<span class="op">~</span>transfers_out[<span class="st">'_conference'</span>].isin(power_conferences) <span class="op">&amp;</span> <span class="op">~</span>transfers_out[<span class="st">'_origin'</span>].<span class="bu">str</span>.contains(<span class="st">'Notre Dame'</span>)]</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Scatter plots</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].scatter(power_five_transfers[<span class="st">'avg_stars'</span>], power_five_transfers[<span class="st">'total_transfers_out'</span>], alpha<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x0, y0, <span class="bu">id</span> <span class="kw">in</span> <span class="bu">zip</span>(power_five_transfers[<span class="st">'avg_stars'</span>], power_five_transfers[<span class="st">'total_transfers_out'</span>], power_five_transfers[<span class="st">'_id'</span>]):</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    ab <span class="op">=</span> AnnotationBbox(get_image_path(<span class="bu">id</span>), (x0, y0), frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].add_artist(ab)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axvline(power_five_transfers[<span class="st">'avg_stars'</span>].mean(), color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axhline(power_five_transfers[<span class="st">'total_transfers_out'</span>].mean(), color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">'Average Stars'</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylabel(<span class="st">'Total Transfers'</span>)</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlim(<span class="fl">2.5</span>, <span class="fl">3.5</span>)</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylim(<span class="fl">4.5</span>, <span class="dv">110</span>)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">'Power Five Transfers Out (2021-2024)'</span>)</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].grid(<span class="va">True</span>)</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].scatter(g5_transfers[<span class="st">'avg_stars'</span>], g5_transfers[<span class="st">'total_transfers_out'</span>], alpha<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x0, y0, <span class="bu">id</span> <span class="kw">in</span> <span class="bu">zip</span>(g5_transfers[<span class="st">'avg_stars'</span>], g5_transfers[<span class="st">'total_transfers_out'</span>], g5_transfers[<span class="st">'_id'</span>]):</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>    ab <span class="op">=</span> AnnotationBbox(get_image_path(<span class="bu">id</span>), (x0, y0), frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].add_artist(ab)</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axvline(g5_transfers[<span class="st">'avg_stars'</span>].mean(), color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axhline(g5_transfers[<span class="st">'total_transfers_out'</span>].mean(), color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlabel(<span class="st">'Average Stars'</span>)</span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylabel(<span class="st">'Total Transfers'</span>)</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlim(<span class="fl">2.5</span>, <span class="fl">3.5</span>)</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylim(<span class="fl">4.5</span>, <span class="dv">110</span>)</span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">'G5 Transfers Out (2021-2024)'</span>)</span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].grid(<span class="va">True</span>)</span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribution plots</span></span>
<span id="cb16-44"><a href="#cb16-44" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb16-45"><a href="#cb16-45" aria-hidden="true" tabindex="-1"></a>sns.histplot(power_five_transfers[<span class="st">'total_transfers_out'</span>], label<span class="op">=</span><span class="st">"Power 5"</span>, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'#ad0004'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, ax<span class="op">=</span>ax[<span class="dv">0</span>])</span>
<span id="cb16-46"><a href="#cb16-46" aria-hidden="true" tabindex="-1"></a>sns.histplot(g5_transfers[<span class="st">'total_transfers_out'</span>], label<span class="op">=</span><span class="st">"G5"</span>, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'#012d69'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, ax<span class="op">=</span>ax[<span class="dv">0</span>])</span>
<span id="cb16-47"><a href="#cb16-47" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">"Total Transfers"</span>)</span>
<span id="cb16-48"><a href="#cb16-48" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb16-49"><a href="#cb16-49" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">"Distribution of Total Transfers Out"</span>)</span>
<span id="cb16-50"><a href="#cb16-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-51"><a href="#cb16-51" aria-hidden="true" tabindex="-1"></a>sns.histplot(power_five_transfers[<span class="st">'avg_stars'</span>], label<span class="op">=</span><span class="st">"Power 5"</span>, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'#ad0004'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, ax<span class="op">=</span>ax[<span class="dv">1</span>])</span>
<span id="cb16-52"><a href="#cb16-52" aria-hidden="true" tabindex="-1"></a>sns.histplot(g5_transfers[<span class="st">'avg_stars'</span>], label<span class="op">=</span><span class="st">"G5"</span>, kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'#012d69'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, ax<span class="op">=</span>ax[<span class="dv">1</span>])</span>
<span id="cb16-53"><a href="#cb16-53" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlabel(<span class="st">"Average Stars"</span>)</span>
<span id="cb16-54"><a href="#cb16-54" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb16-55"><a href="#cb16-55" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">"Distribution of Transfer Out Star Ratings"</span>)</span>
<span id="cb16-56"><a href="#cb16-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-57"><a href="#cb16-57" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb16-58"><a href="#cb16-58" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb16-59"><a href="#cb16-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-60"><a href="#cb16-60" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect power for average starts out</span></span>
<span id="cb16-61"><a href="#cb16-61" aria-hidden="true" tabindex="-1"></a>n_power_five <span class="op">=</span> <span class="bu">len</span>(power_five_transfers)</span>
<span id="cb16-62"><a href="#cb16-62" aria-hidden="true" tabindex="-1"></a>n_g5 <span class="op">=</span> <span class="bu">len</span>(g5_transfers)</span>
<span id="cb16-63"><a href="#cb16-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-64"><a href="#cb16-64" aria-hidden="true" tabindex="-1"></a>std_power_five <span class="op">=</span> power_five_transfers[<span class="st">'avg_stars'</span>].std()</span>
<span id="cb16-65"><a href="#cb16-65" aria-hidden="true" tabindex="-1"></a>std_g5 <span class="op">=</span> g5_transfers[<span class="st">'avg_stars'</span>].std()</span>
<span id="cb16-66"><a href="#cb16-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-67"><a href="#cb16-67" aria-hidden="true" tabindex="-1"></a>pooled_std <span class="op">=</span> np.sqrt(((n_power_five <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> std_power_five<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> (n_g5 <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> std_g5<span class="op">**</span><span class="dv">2</span>) <span class="op">/</span> (n_power_five <span class="op">+</span> n_g5 <span class="op">-</span> <span class="dv">2</span>))</span>
<span id="cb16-68"><a href="#cb16-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-69"><a href="#cb16-69" aria-hidden="true" tabindex="-1"></a>cohens_d <span class="op">=</span> (power_five_transfers[<span class="st">'avg_stars'</span>].mean() <span class="op">-</span> g5_transfers[<span class="st">'avg_stars'</span>].mean()) <span class="op">/</span> pooled_std</span>
<span id="cb16-70"><a href="#cb16-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-71"><a href="#cb16-71" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cohen's D: </span><span class="sc">{</span>cohens_d<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="an-honest-conversation-about-the-transfer-portal_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="an-honest-conversation-about-the-transfer-portal_files/figure-html/cell-14-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's D: 1.89</code></pre>
</div>
</div>
<p>These charts tell me that there is a lot of movement within P5 and G5 and, if anything, there are more players going from the Power 5 level to the Group of 5 level. If the number of players coming in are equal and the number of players going out from P5 schools is greater than the number of players going out from G5 schools, that necessarily means that more players are going from P5 to G5 than vise versa.</p>
<p>Further, and perhaps more importantly, is the Cohen’s D value that we are getting. The effect size of players transferring <em>in</em> was 1.6 indicating stronger players coming in to Power 5 schools. However, the effect size of players transferring <em>out</em> of Power 5 schools is even strong at <strong>1.89</strong>. Obviously there are prep recruits to consider when thinking about the makeup of a college football team, but as far as the transfer portal is concerned Power Five schools have been operating a net talent loss.</p>
<div id="cell-26" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>transfers_in <span class="op">=</span> transfers.rename({<span class="st">'avg_stars'</span>: <span class="st">'avg_stars_in'</span>}, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>transfers_out <span class="op">=</span> transfers_out.rename({<span class="st">'avg_stars'</span>: <span class="st">'avg_stars_out'</span>}, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>transfers_by_team <span class="op">=</span> transfers_in.merge(transfers_out, how<span class="op">=</span><span class="st">'left'</span>, on<span class="op">=</span><span class="st">'_id'</span>).drop([<span class="st">'_conference_y'</span>, <span class="st">'_origin'</span>], axis<span class="op">=</span><span class="dv">1</span>).rename({<span class="st">'_conference_x'</span>: <span class="st">'_conference'</span>, <span class="st">'_destination'</span>: <span class="st">'team'</span>}, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>transfers_by_team[<span class="st">'net_stars'</span>] <span class="op">=</span> transfers_by_team[<span class="st">'avg_stars_in'</span>] <span class="op">-</span> transfers_by_team[<span class="st">'avg_stars_out'</span>]</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>transfers_by_team[<span class="st">'net_transfers'</span>] <span class="op">=</span> transfers_by_team[<span class="st">'total_transfers_in'</span>] <span class="op">-</span> transfers_by_team[<span class="st">'total_transfers_out'</span>]</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>p5_transfers <span class="op">=</span> transfers_by_team[transfers_by_team[<span class="st">'_conference'</span>].isin(power_conferences) <span class="op">|</span> transfers_by_team[<span class="st">'team'</span>].<span class="bu">str</span>.contains(<span class="st">'Notre Dame'</span>)]</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>g5_transfers <span class="op">=</span> transfers_by_team[<span class="op">~</span>transfers_by_team[<span class="st">'_conference'</span>].isin(power_conferences) <span class="op">&amp;</span> <span class="op">~</span>transfers_by_team[<span class="st">'team'</span>].<span class="bu">str</span>.contains(<span class="st">'Notre Dame'</span>)]</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].scatter(p5_transfers[<span class="st">'avg_stars_in'</span>], p5_transfers[<span class="st">'avg_stars_out'</span>], alpha<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x0, y0, <span class="bu">id</span> <span class="kw">in</span> <span class="bu">zip</span>(p5_transfers[<span class="st">'avg_stars_in'</span>], p5_transfers[<span class="st">'avg_stars_out'</span>], p5_transfers[<span class="st">'_id'</span>]):</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    ab <span class="op">=</span> AnnotationBbox(get_image_path(<span class="bu">id</span>), (x0, y0), frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].add_artist(ab)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">'Average Stars In'</span>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylabel(<span class="st">'Average Stars Out'</span>)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].annotate(<span class="st">'Better players out'</span>, xy<span class="op">=</span>(<span class="fl">2.75</span>, <span class="fl">3.4</span>))</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].annotate(<span class="st">'Better players in'</span>, xy<span class="op">=</span>(<span class="fl">3.4</span>, <span class="fl">2.8</span>))</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlim(<span class="fl">2.7</span>, <span class="fl">3.7</span>)</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylim(<span class="fl">2.5</span>, <span class="fl">3.5</span>)</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axline(xy1<span class="op">=</span>(<span class="fl">2.7</span>, <span class="fl">2.7</span>), slope<span class="op">=</span><span class="dv">1</span>, color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">'Power Five Transfers (2021-2024)'</span>)</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].grid(<span class="va">True</span>)</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].scatter(g5_transfers[<span class="st">'avg_stars_in'</span>], g5_transfers[<span class="st">'avg_stars_out'</span>], alpha<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x0, y0, <span class="bu">id</span> <span class="kw">in</span> <span class="bu">zip</span>(g5_transfers[<span class="st">'avg_stars_in'</span>], g5_transfers[<span class="st">'avg_stars_out'</span>], g5_transfers[<span class="st">'_id'</span>]):</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>    ab <span class="op">=</span> AnnotationBbox(get_image_path(<span class="bu">id</span>), (x0, y0), frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].add_artist(ab)</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlabel(<span class="st">'Average Stars In'</span>)</span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylabel(<span class="st">'Average Stars Out'</span>)</span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlim(<span class="fl">2.7</span>, <span class="fl">3.7</span>)</span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylim(<span class="fl">2.5</span>, <span class="fl">3.5</span>)</span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].annotate(<span class="st">'Better players out'</span>, xy<span class="op">=</span>(<span class="fl">2.75</span>, <span class="fl">3.4</span>))</span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].annotate(<span class="st">'Better players in'</span>, xy<span class="op">=</span>(<span class="fl">3.4</span>, <span class="fl">2.8</span>))</span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axline(xy1<span class="op">=</span>(<span class="fl">2.7</span>, <span class="fl">2.7</span>), slope<span class="op">=</span><span class="dv">1</span>, color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">'G5 Transfers (2021-2024)'</span>)</span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].grid(<span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="an-honest-conversation-about-the-transfer-portal_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This plot broke my brain a bit. How is it possible that so many Power Five teams have better players coming in than going out, if we know that there are more players transferring away from the P5 than there are transferring to the G5? Until I saw that damned Script A again that has shown up in a class of its own on every plot that I’ve made so far.</p>
<div id="cell-28" class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].scatter(p5_transfers[<span class="st">'net_transfers'</span>], p5_transfers[<span class="st">'net_stars'</span>], alpha<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x0, y0, <span class="bu">id</span> <span class="kw">in</span> <span class="bu">zip</span>(p5_transfers[<span class="st">'net_transfers'</span>], p5_transfers[<span class="st">'net_stars'</span>], p5_transfers[<span class="st">'_id'</span>]):</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    ab <span class="op">=</span> AnnotationBbox(get_image_path(<span class="bu">id</span>), (x0, y0), frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">0</span>].add_artist(ab)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">'Net Transfers'</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylabel(<span class="st">'Net Average Stars'</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">'Power Five Net Transfers (2021-2024)'</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlim(<span class="op">-</span><span class="dv">55</span>, <span class="dv">70</span>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylim(<span class="op">-</span><span class="fl">0.3</span>, <span class="fl">.5</span>)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].grid(<span class="va">True</span>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].scatter(g5_transfers[<span class="st">'net_transfers'</span>], g5_transfers[<span class="st">'net_stars'</span>], alpha<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x0, y0, <span class="bu">id</span> <span class="kw">in</span> <span class="bu">zip</span>(g5_transfers[<span class="st">'net_transfers'</span>], g5_transfers[<span class="st">'net_stars'</span>], g5_transfers[<span class="st">'_id'</span>]):</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    ab <span class="op">=</span> AnnotationBbox(get_image_path(<span class="bu">id</span>), (x0, y0), frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>    ax[<span class="dv">1</span>].add_artist(ab)</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlabel(<span class="st">'Net Transfers'</span>)</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylabel(<span class="st">'Net Average Stars'</span>)</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">'G5 Net Transfers (2021-2024)'</span>)</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlim(<span class="op">-</span><span class="dv">55</span>, <span class="dv">70</span>)</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylim(<span class="op">-</span><span class="fl">0.3</span>, <span class="fl">.5</span>)</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].grid(<span class="va">True</span>)</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Power Five Average Net Transfers: </span><span class="sc">{</span>p5_transfers[<span class="st">'net_transfers'</span>]<span class="sc">.</span>mean()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"G5 Average Net Transfers: </span><span class="sc">{</span>g5_transfers[<span class="st">'net_transfers'</span>]<span class="sc">.</span>mean()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Power Five Average Net Stars: </span><span class="sc">{</span>p5_transfers[<span class="st">'net_stars'</span>]<span class="sc">.</span>mean()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"G5 Average Net Stars: </span><span class="sc">{</span>g5_transfers[<span class="st">'net_stars'</span>]<span class="sc">.</span>mean()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="an-honest-conversation-about-the-transfer-portal_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Power Five Average Net Transfers: -13.557142857142857
G5 Average Net Transfers: 8.370967741935484
Power Five Average Net Stars: 0.05454902936543176
G5 Average Net Stars: 0.03710712681054378</code></pre>
</div>
</div>
<p>Power Five schools are losing, on average, 13.56 players to the transfer portal each year while Group of Five teams are <em>gaining</em> 8.37 players per year. So while the average stars of the players coming in to a P5 school is increasing, the number of bodies available for that team, through the transfer portal, is decreasing. Meanwhile, G5 schools are actually getting more, better players through the transfer portal.</p>
</section>
<section id="who-is-really-hurt-by-this" class="level2">
<h2 class="anchored" data-anchor-id="who-is-really-hurt-by-this">Who is Really Hurt By This?</h2>
<p>Given all of this information, I think the noise being made my G5 coaches about their players being poached is largely overstated. I understand the want for continuity and keeping players in your system. However, this data tells me that G5 schools are fairing much better in the transfer portal than power conference teams.</p>
<p>Who really has a right to be throwing a fit are the high school players who are yet to play a down of college football. There are only so many roster spots available in college football and not everyone is a blue chip recruit. Most of them are two or three star kids. If the players that didn’t make it at the P5 level are going to the G5, and the P5 schools are backfilling with blue chip guys, what happens to those two and three star players? Surely some of them will go to the Wyoming and Central Michigan’s of the world - the G5 teams with net negative transfers. But most of them will need to move down FCS or DII.</p>
<p>There is nothing wrong with playing at that level of football. I went to an FCS school and a handful of the players on the football team while I was there ended up in the NFL. If you’re good enough, they will find you. But for the vast majority of players, the players who go to school, play football on a scholarship, and then get a job like you and me, the difference in level can mean thousands of dollars in scholarship money lost. FCS schools have fewer scholarships to begin with, and even then those scholarships are generally not full rides.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This is not an admonishment of the Transfer Portal or the state of college football. There are plenty of unknowns in the sport and navigating these uncharted waters is bound to lead to some growing pains. I think it is fair to have criticisms of unlimited player transferring. But the next time someone tells you that it is killing the Group of Five teams, you will know that that is not true.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/bendemouth\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>