<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-05-28">
<meta name="description" content="Does a fighter’s physical characteristics make a real difference?">

<title>The Size of the Dog In The Fight – bendemouth.github.io</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-bf19b75f51ea680c8de03e84aa65eabd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">bendemouth.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/bendemouth"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bsky.app/profile/turbocorn.bsky.social"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://linkedin.com/in/bendemouth"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text">LinkedIn</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">The Size of the Dog In The Fight</h1>
                  <div>
        <div class="description">
          Does a fighter’s physical characteristics make a real difference?
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">MMA</div>
                <div class="quarto-category">Gambling</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 28, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>For as long as humanity has been roaming the earth, fighting has been a part of our culture. Whether it be fighting over food as nomads, fighting over land in the feudal age, or fighting for natural resources in our current era, man always seems to find a reason for fighting.</p>
<p>Combat is not always confined to war, though. For centuries, we have been fighting for sport as well. Boxing matches have been recorded as far back as 6,000 BC and wrestling is thought to have been a part of the first ever Olympics. Nearly every culture across all history has had some form of combat sport as part of their culture.</p>
<p>With this apparent obsession with violent competition, it is natural to look for any edge that one combatant may have over the other. Turn on any boxing or MMA match and you are likely to see the “Tale of the Tape” displayed before the bout, showing each fighter’s age, record, height, reach, and weight. Of course, MMA has developed to now have weight classes so weight is less of a factor, but <a href="https://www.youtube.com/watch?v=kCdh-PXYZMs&amp;ab_channel=UFCClassics">that wasn’t always the case</a>.</p>
<p>Does any of this information really matter though? Does the taller fighter or the fighter with a longer reach really have an advantage, or are we just looking for advantages where there are none? Certainly any insights found here will be broad; actual fighting skill is paramount. For example, I am 6’ 4” 190 lbs, but I would not want to get into the octagon with a man like Dustin Poirier, who stands 5’ 9” and has fought at 145 and 155 lbs. <a href="https://www.youtube.com/watch?v=cLcZTYIZQcI&amp;ab_channel=UFC">I am not built for this</a>. But perhaps among professional fighters with equal, or at least comparable, we can learn something.</p>
<p>The data used for this project comes from <a href="https://www.kaggle.com/datasets/mdabbert/ultimate-ufc-dataset?resource=download">Kaggle user mdabbert</a> and contains data from the UFC dating back to 2010. There are 118 columns available in this dataset. We’ll mostly focus on the columns containing information about the physical attributes of our fighters.</p>
<div id="ccf63efc385a5eeb" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:05:06.782793Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:05:06.738589Z&quot;}" data-execution_count="46">
<div class="cell-output cell-output-stdout">
<pre><code>Index(['RedFighter', 'BlueFighter', 'RedOdds', 'BlueOdds', 'RedExpectedValue',
       'BlueExpectedValue', 'Date', 'Location', 'Country', 'Winner',
       ...
       'FinishDetails', 'FinishRound', 'FinishRoundTime', 'TotalFightTimeSecs',
       'RedDecOdds', 'BlueDecOdds', 'RSubOdds', 'BSubOdds', 'RKOOdds',
       'BKOOdds'],
      dtype='object', length=118)</code></pre>
</div>
</div>
<p>With this data in mind, let’s take a look at how many fights have occurred at each weight class, and a table of the weights for each for reference.</p>
<div id="83b2b92b569dd261" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:05:06.794235Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:05:06.788798Z&quot;}" data-execution_count="47">
<div class="cell-output cell-output-display" data-execution_count="47">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Weight Limit (Lbs.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Strawweight (W only)</td>
<td>115</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Flyweight</td>
<td>125</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Bantamweight</td>
<td>135</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Featherweight</td>
<td>145</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Lightweight</td>
<td>155</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Welterweight</td>
<td>170</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Middleweight</td>
<td>185</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Light Heavyweight</td>
<td>205</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Heavyweight</td>
<td>265</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="d69a1a5175832524" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:05:06.938132Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:05:06.833765Z&quot;}" data-execution_count="48">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>You may notice one extra class that is not in the weight class table: Catch Weight. That is just a term used for when a bout does not fit neatly into one of the existing weight classes. It is generally used when one or both fighters miss weight but still agree to continue with the fight.</p>
<p>The lightweight division is certainly the most popular division in the UFC. It is a good balance of speed and power, and has featured superstars and fan favorites like Conor McGregor, Khabib Nurmagomedov, Nate Diaz, Charles Olivera, Max Holloway, and the previously mentioned Dustin Poirier to name a few.</p>
<div id="8b79b4045b15757f" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:05:07.182011Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:05:06.957147Z&quot;}" data-execution_count="49">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As expected, the distribution of height and reach roughly follows with weight classes - as weight goes up, so does reach and height. I do find it interesting, though, that most of the outliers at the heavier classes are <em>below</em> the class average. This doesn’t say anything to the success of any particular fighter, though, just an observation.</p>
<div id="e90301920d55a2" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:05:07.256838Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:05:07.187016Z&quot;}" data-execution_count="50">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Interestingly, in fights where there is a height difference the shorter fighter wins more often, though the advantage is small. The fighter with the longer reach does win more frequently, but again, the advantage is tiny. As previously mentioned though, actual fight skill is most important. There are many fights in here that, on paper, are slated to be one-sided affairs.</p>
<p>It may be more advantageous for our purposes to look at fights where both sides are expected to be somewhat evenly matched.</p>
<div id="d8ef345243e0adb5" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:05:07.373414Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:05:07.303990Z&quot;}" data-execution_count="51">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>I used underdog odds being shorter than +200 as my cutoff for what I considered an even match up. It’s an arbitrary number, to be sure, but we don’t see a real change from looking at all fights, and it doesn’t change when lowering the threshold to +150 either. This is a bit more surprising to me. Between supposedly equally matched fighters, I would have expected physical advantages, no matter how slight, to have a more pronounced effect. But that doesn’t seem to be the case.</p>
<p>This isn’t a small subset of fights either. 3,937 of the 6,528 fights (60.3%) recorded met the criteria for a “close” fight.</p>
<p>There are, however, a couple of classes where height and reach <em>does</em> make a sizable impact: Heavyweight, Light Heavyweight, Women’s Bantamweight, and Women’s Featherweight.</p>
<div id="b07bec311c75c7a3" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:05:07.594618Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:05:07.378419Z&quot;}" data-execution_count="52">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>It’s interesting to note that these are the two heaviest divisions for both men and women. In fact, the trend seems to be that as the weight increases for the fight, height and reach become more important.</p>
<div id="ee60252bbb545d0a" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:18:37.170628Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:18:35.751909Z&quot;}" data-execution_count="53">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="heavyweights" class="level2">
<h2 class="anchored" data-anchor-id="heavyweights">Heavyweights</h2>
<p>The heavyweight division is unique among UFC weight classes. In other weight classes, fighters are generally cutting weight to come in right at the weight limit, meaning there is almost always no weight advantage. Generally, there are also only 10 lbs between weight classes, with a couple having 15 lbs between them. Heavyweights on the other hand have 60 lbs between their 265 lbs weight limit and the 205 lbs weight limit for light heavyweight.</p>
<p>This massive gap between weight classes means that there is a third physical characteristic that becomes potentially advantageous at the heavyweight division: weight.</p>
<div id="0f932169" class="cell" data-execution_count="54">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Whereas in the other weight classes most fighters are coming in right at the weight limit, heavyweight has a median weight of 253 lbs, 12 lbs less than the class’ weight limit! As far as I can tell (using <a href="https://www.tapology.com">Tapology’s fight database</a>), the UFC has not had a champion weigh in at the 265 lbs weight limit since Brock Lesnar won the belt in 2010. Lesnar weighed in at 264 lbs in his subsequent title defense and lost the title to Cain Velasquez who weighed in for the fight at 244 lbs.</p>
<p>This great variance in fighter weight naturally leads to match ups where there is a big difference between the two at the time of the fight. As demonstrated above, Lesnar and Velasquez had a 20 lbs weight difference for a championship fight.</p>
<div id="70d57e056a08a796" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:05:07.729764Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:05:07.643624Z&quot;}" data-execution_count="55">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>To put this into perspective, the typical difference between two fighters at heavyweight, 12 lbs, is greater than the difference between two fighters at completely different weight classes at the smaller classes!</p>
<p>But does the fighter with the greater weight have any sort of advantage?</p>
<div id="d121bb5c0a4c42cf" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2025-06-03T15:05:07.797647Z&quot;,&quot;start_time&quot;:&quot;2025-06-03T15:05:07.755777Z&quot;}" data-execution_count="56">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-12-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In these match ups between evenly matched heavyweights, the weight seems to play an. And it makes sense from a physics perspective. If we know that more mass leads to more force (assuming acceleration remains the same), then those fighters that weigh more can punch harder, doing more damage to their opponent if not knocking them out.</p>
<p>There are strategies to deal with an opponent who is taller or has a longer reach, but there is no way to out-maneuver physics.</p>
</section>
<section id="on-betting" class="level2">
<h2 class="anchored" data-anchor-id="on-betting">On Betting</h2>
<p>While humans love fighting, they perhaps love gambling even more. And with the rise in legalized sports gambling, many people are looking for any edge over the books that can help them make a few quick dollars.</p>
<p>It has already been demonstrated that, in most weight classes, there is not a clear advantage to height and reach, especially at the lower weight classes. But that doesn’t necessarily mean that it can’t a profitable strategy to bet on the fighter with the advantage.</p>
<div id="fd9461f2" class="cell" data-execution_count="57">
<div class="cell-output cell-output-stdout">
<pre><code>Average profit betting on taller fighter: $-3.60
Average profit betting on fighter with longer reach: $-4.61</code></pre>
</div>
</div>
<p>Unfortunately, we aren’t beating the books by blindly betting on physical characteristics. At least not across all fights. As demonstrated above, however, the advantage becomes a little bit greater at the heavier weight classes. Perhaps that is where the money is.</p>
<div id="9e7ad34b" class="cell" data-execution_count="58">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the-size-of-the-dog-in-the-fight_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Well, we’ve finally done it. We’ve found a way to beat Vegas (This is not gambling advice. Please do not use this strategy. A $8.38 average profit on a $100 bet is not worth the losses you will surely incur along the way.).</p>
<p>Earlier it was discussed that the winning percentages that stood out when looking at height and reach were to two heaviest weight class for each sex. When betting, of those classes discussed, only the women’s bantamweight division is profitable for both height and reach, the men’s light heavyweight and heavyweight divisions are only profitable by reach, and the women’s featherweight division is not profitable for either. The men’s featherweight division appears profitable for reach and the men’s welterweight division appears profitable for height. Despite the winning percentage of taller and longer fighters being so large for the women’s featherweight division, those fighters must be such large favorites that they are not worth betting on.</p>
<p>Finally, let’s take a look at the betting for the heavier heavyweights.</p>
<div id="b46188ce" class="cell" data-execution_count="59">
<div class="cell-output cell-output-stdout">
<pre><code>Average profit betting on heavier fighter at heavyweight division: $-6.30</code></pre>
</div>
</div>
<p>Similar to the phenomenon seen at the women’s featherweight division, we see the same thing when observing the effect of weight at the heavyweight division. The heavier fighter wins more frequently, but betting on them is not a profitable strategy. If you were to bet $100 on the heavier fighter in every heavyweight bout, you would expect to lose $6.31 on average.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Ultimately I am surprised that there is such little effect from physical characteristics across all divisions. Any advantages found are confined to a couple of divisions.</p>
<p>I enjoy watching mixed martial arts and generally watch it with a group of friends. When the tale of the tape comes up before a fight where we are unfamiliar with the fighters, we all speculate on who has the advantage based on their physical traits. It’s a way for us to get invested in the fight without any prior knowledge. We are wasting our breath, it appears.</p>
<p>It’s also interesting to see how much the sport varies between weights, even those that are close to each other. Going back and looking at the charts, there is always a break in the trend between featherweight and lightweight even though the two are separated by just 10 lbs and there are plenty of fighters who have fought in both divisions over the years. To me, this is a perfect demonstration of how the sport changes and fighters may alter their strategies at each weight class.</p>
<p>I didn’t find a perfect way to predict fights, but I think this gives some more clear insight into what does and does not matter in a fight, and drives home the point that the old saying is true: it’s not the size of the dog in the fight, it’s the size of the fight in the dog.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/bendemouth\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>